spring:
  application:
    name:
      manage
  datasource:
    url: ${SPRING_DATASOURCE_URL :jdbc:postgresql://localhost:9871/manage}
    username: ${SPRING_DATASOURCE_USERNAME :postgres}
    password: ${SPRING_DATASOURCE_PASSWORD :manage}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true

server:
  port: ${SPRING_PORT :1243}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    com:
      baeldung:
        cloud:
          openfeign:
            client: DEBUG

jwt:
  secret: ${JWT_SECRET :844c1a09b1e84fb767916edce5f6fbad1401c588a0f10fb7de79c245324c4d7d3e6c62b5aec4a168cc14f957946ced574ad38cb6b44d732641f307158afd19fb}
  access: 86400
  refresh: 86400